package purple

import "gopkg.in/yaml.v2"

type TestSuiteSpec struct {
	AttackTechnique string `yaml:"attack_technique"`
	DisplayName string `yaml:"display_name"`
	Tests []AtomicTestSpec `yaml:"atomic_tests"`
}

type AtomicTestSpec struct {
	Name               string                            `yaml:"name"`
	AutoGeneratedGUID  string                            `name:"auto_generated_guid"`
	Description        string                            `name:"description"`
	SupportedPlatforms []string                          `yaml:"supported_platforms"`
	InputArguments     map[string]TestExecutionArguments `yaml:"input_arguments"`
	Execution          TestExecutionSpec                 `yaml:"executor"`
}

type TestExecutionSpec struct {
	Name string `yaml:"name"`
	ElevationRequired bool `yaml:"elevation_required"`
	PrereqCommand string `yaml:"prereq_command"`
	Command string `yaml:"command"`
	CleanupCommand string `yaml:"cleanup_command"`
}

type TestExecutionArguments struct {
	Description string `yaml:"description"`
	Type string `yaml:"type"`
	Default string `yaml:"default"`
}

func ParseART(yamldata string) (*TestSuiteSpec, error) {
	spec := TestSuiteSpec{}

	err := yaml.Unmarshal([]byte(yamldata), &spec)

	return &spec, err
}