# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - staging
      - develop
  pull_request:
    branches:
      - master
      - staging
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0' # The Go version to download (if necessary) and use.

      # Install all the dependencies
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y build-essential
          go version
          go mod tidy

      # Run vet
      - name: vet
        run: make vet

      # Run tests
      - name: test
        run: make test coverage

      # Build it
      - name: build
        run: make build

#  # The "deploy" workflow
#  deploy:
#    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    needs: [build] # Only run this workflow when "build" workflow succeeds
#    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }} # Only run this workflow if it is master branch on push event
#    steps:
#      - uses: actions/checkout@v2
#
#      # Deploy to Docker registry
#      - name: Deploy to Docker registry
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          repository: wurb/purple
#          tag_with_ref: true